### ISSUE TITLE
Error message when displaying dashboard in embed mode

### ISSUE THREAD

**Issue by thib66** [emoncms/dashboard#235]
Hello,
here is the error message when the Graph module is installed and enabled :
Fatal error: Uncaught Error: Call to a member function fetch_array() on bool in /home/www/emoncms/Modules/graph/graph_model.php:95 Stack trace: #0 /home/www/emoncms/Modules/graph/widget/graph_widget.php(16): Graph->getall(2) #1 /home/www/emoncms/Modules/dashboard/Views/loadwidgets.php(44): require_once('/home/...') #2 /home/www/emoncms/Modules/dashboard/Views/loadwidgets.php(24): load_widget('Modules/graph/w...', 'graph') #3 /home/www/emoncms/Modules/dashboard/Views/dashboard_view.php(37): require_once('/home/...') #4 /home/www/emoncms/core.php(73): include('/home/...') #5 /home/www/emoncms/Modules/dashboard/dashboard_controller.php(53): view('Modules/dashboa...', Array) #6 /home/www/emoncms/core.php(60): dashboard_controller() #7 /home/www/emoncms/index.php(215): controller('dashboard') #8 {main} thrown in /home/www/emoncms/Modules/graph/graph_model.php on line 95
The url on the embed dashboard is like this : 
https://website.net/emoncms/dashboard/view?id=3&embed=1&apikey=xxxx"

<details><summary>Server Information</summary>

# Server Information
## Emoncms
 
- **Version** :- 10.1.6-beta
- **Modules** :- Administration | Dashboard v2.0.4 | Device v2.0.1 | EventProcesses | Feed | Graph v2.0.3 | Input | CoreProcess | Schedule | Time | User | Visualisation
- **Git** :- 
     - **URL** :- origin
     - **Branch** :- - **Describe** :- 
## Server
 
- **OS** :- Linux 4.14.119-ovh-vps-grsec-zfs-classid
- **Host** :- webm158.cluster014.gra.hosting.ovh.net | webm158.cluster014.gra.hosting.ovh.net | (51.83.10.145)
- **Date** :- 2019-09-06 18:00:29 CEST
- **Uptime** :- 16:00:29 up 109 days,  5:52,  0 users,  load average: 0,89, 0,89, 0,91

## Memory
 
- **RAM** :- Used: 44,66%
    - **Total** :- 31,43 GB
     - **Used** :- 14,04 GB
     - **Free** :- 17,39 GB
- **Swap** :- Used: 3,98%
    - **Total** :- 511 MB
     - **Used** :- 20,32 MB
     - **Free** :- 490,68 MB

## HTTP
 
- **Server** :- Apache HTTP/1.1 CGI/1.1 443

## MySQL
 
- **Version** :- 5.6.43-log
- **Host** :- localhost:6379 (127.0.0.1)
- **Date** :- 2019-09-06 18:00:29 (UTC 02:00‌​)
- **Stats** :- Uptime: 1309310  Threads: 27  Questions: 226958974  Slow queries: 7  Opens: 5309269  Flush tables: 1  Open tables: 64  Queries per second avg: 173.342

## PHP
 
- **Version** :- 7.3.6 (Zend Version 3.3.6)
- **Modules** :- bcmath v7.3.6 | bz2 v7.3.6 | calendar v7.3.6 | cgi-fcgi | Core v7.3.6 | ctype v7.3.6 | curl v7.3.6 | date v7.3.6 | dba v7.3.6 | dom v20031129 | exif v7.3.6 | fileinfo v7.3.6 | filter v7.3.6 | ftp v7.3.6 | gd v7.3.6 | gettext v7.3.6 | gmp v7.3.6 | hash v7.3.6 | iconv v7.3.6 | imagick v3.4.3RC1 | imap v7.3.6 | intl v7.3.6 | ionCube Loader | json v1.7.0 | libxml v7.3.6 | mbstring v7.3.6 | memcached v3.1.0-dev | mongodb v1.5.0-dev | mysqli v7.3.6 | mysqlnd vmysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $ | openssl v7.3.6 | pcre v7.3.6 | PDO v7.3.6 | pdo_mysql v7.3.6 | pdo_pgsql v7.3.6 | pdo_sqlite v7.3.6 | pgsql v7.3.6 | Phar v7.3.6 | posix v7.3.6 | pspell v7.3.6 | redis v3.1.2 | Reflection v7.3.6 | session v7.3.6 | SimpleXML v7.3.6 | soap v7.3.6 | sockets v7.3.6 | sodium v7.3.6 | SPL v7.3.6 | sqlite3 v7.3.6 | standard v7.3.6 | sysvmsg v7.3.6 | sysvsem v7.3.6 | sysvshm v7.3.6 | tokenizer v7.3.6 | wddx v7.3.6 | xml v7.3.6 | xmlreader v7.3.6 | xmlrpc v7.3.6 | xmlwriter v7.3.6 | xsl v7.3.6 | Zend OPcache v7.3.6 | zip v1.15.4 | zlib v7.3.6
</details>

<details><summary>Client Information</summary>

# Client Information
## HTTP
 
- **Browser** :- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
- **Language** :- fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3

## Window
 
- **Size** :- 1263 x 910

## Screen
 
- **Resolution** :- 1280 x 1024
</details>

Let me know if you need further details,
Regards,

**Comment by thib66** [comment]
Using the new settings.ini instead of my existing settings.php and updating the database have solved the problem.
